"""Keep the selected M1 kernel reference in Git without the full capture archive.

Uses deduplicated, gzip-compressed chunks in bounded pack files. Extraction and
verification need only Python's standard library, on macOS or Asahi Linux.
This packages observations; it never submits an ANE program or reads MMIO.
"""
from __future__ import annotations

import argparse
import gzip
import hashlib
import json
from pathlib import Path, PurePosixPath
import struct

CHUNK_BYTES = 1024 * 1024
PACK_BYTES = 16 * 1024 * 1024
ARCHIVE_SHA = "7862a6b32164023818dc47fea18aeba8a633f2a74d7da651af33b1894bed42d2"


def sha256(path):
    result = hashlib.sha256()
    with Path(path).open("rb") as stream:
        for chunk in iter(lambda: stream.read(CHUNK_BYTES), b""):
            result.update(chunk)
    return result.hexdigest()


def relative_path(value):
    path = PurePosixPath(value)
    if path.is_absolute() or ".." in path.parts or not path.parts:
        raise ValueError(f"Expected a relative artifact path: {value}")
    return Path(*path.parts)


def selected_files(capture):
    summary = json.loads((capture / "ane-summary.json").read_text())
    rows = summary["selected_cases"]
    if len(rows) != 20 or len({r["label"] for r in rows}) != 20:
        raise ValueError("Need exactly 20 distinct selected finite captures")
    files = set()
    for row in rows:
        if not row["finite"] or not row["receipt"]["runtime_evaluated"] or row["evaluated_executable_found"]:
            raise ValueError(f"Unexpected selected capture provenance: {row['label']}")
        case = capture / relative_path(row["case"])
        # Complete offline HWX already includes all compiled coefficients.
        # Separate decoded segment payloads are regenerated byte-for-byte below.
        # Original model BLOBs and runtime temporary copies remain in the archive.
        for p in case.rglob("*"):
            if not p.is_file(): continue
            parts = p.relative_to(case).parts
            if "evaluated-runtime" in parts or "weights" in parts or "payloads" in parts:
                continue
            files.add(p)
        golden = capture / relative_path(row["golden"])
        if sha256(golden) != row["golden_sha256"]:
            raise ValueError(f"Golden hash changed: {row['label']}")
        files.add(golden)
        request = capture / relative_path(row["request_surface_capture"])
        files.add(request)
        files.update(request.parent.glob("initial-*.bin"))
        files.add(request.parent / "output-0.bin")
        if sha256(request.parent / "output-0.bin") != row["golden_sha256"]:
            raise ValueError(f"Request surface output differs from golden: {row['label']}")
        hwx = case / "capture/offline-hwx/model.hwx"
        decoded = json.loads(hwx.with_name("model.hwx-decoded").joinpath("container.json").read_text())
        if decoded["architecture"] != "H13G" or decoded["isa_version"] != 7 or decoded["sha256"] != sha256(hwx):
            raise ValueError(f"Wrong architecture or decoded program hash: {row['label']}")
    for name in ("manifest.json", "capture-manifest.json", "ane-summary.json", "decoded-manifest.json",
                 "ane-parser-crosscheck.json", "build/chip.txt", "build/macos.txt", "build/compiler.txt",
                 "build/python-packages.txt", "build/repo-commit.txt", "build/ane-ioreg.txt",
                 "build/capture-sorted-inputs.m", "build/decode_capture.py", "build/crosscheck_ane.py"):
        files.add(capture / name)
    files.update(p for p in (capture / "build/ane-reference").rglob("*") if p.is_file())
    return summary, sorted(files)


def pack(capture, output):
    if output.exists():
        raise ValueError(f"Use a fresh output directory: {output}")
    summary, files = selected_files(capture)
    input_manifest = json.loads((capture / "manifest.json").read_text())
    capture_manifest = json.loads((capture / "capture-manifest.json").read_text())
    expected = dict(capture_manifest["captured_files"])
    expected.update(input_manifest["tools"])
    for case in input_manifest["cases"]:
        expected.update({str(PurePosixPath(case["directory"]) / name): digest
                         for name, digest in case["files"].items()})
    if sha256(capture / "manifest.json") != capture_manifest["input_manifest_sha256"]:
        raise ValueError("Input manifest no longer matches the capture")
    for path in files:
        name = path.relative_to(capture).as_posix()
        if name in expected and sha256(path) != expected[name]:
            raise ValueError(f"Source capture hash mismatch: {name}")

    output.mkdir(parents=True)
    manifest = {"schema": 1, "architecture": "H13G", "cpu_subtype": 4, "isa_version": 7,
                "chunk_bytes": CHUNK_BYTES, "source_archive_sha256": ARCHIVE_SHA,
                "source_input_manifest_sha256": capture_manifest["input_manifest_sha256"],
                "hardware": summary["hardware"], "macos": summary["macos"],
                "golden_provenance": summary["golden_provenance"],
                "selected_cases": summary["selected_cases"],
                "limitations": summary["missing"],
                "offline_hwx_evaluated": False, "linux_replay_verified": False,
                "omitted": ["Original compiler-input weight BLOBs and runtime temporary copies",
                            "Decoded segment payload copies (regenerated from complete HWX at extraction)",
                            "BF16 target checkpoint, failed trials, Instruments recordings, and build binaries"],
                "objects": {}, "files": {}, "packs": {}}
    pack_index, pack_size, stream = -1, 0, None
    try:
        for path in files:
            name = path.relative_to(capture).as_posix()
            recipe = {"bytes": path.stat().st_size, "sha256": sha256(path), "chunks": []}
            with path.open("rb") as source:
                for raw in iter(lambda: source.read(CHUNK_BYTES), b""):
                    digest = hashlib.sha256(raw).hexdigest()
                    recipe["chunks"].append(digest)
                    if digest in manifest["objects"]:
                        continue
                    compressed = gzip.compress(raw, compresslevel=6, mtime=0)
                    if stream is None or pack_size + len(compressed) > PACK_BYTES:
                        if stream is not None: stream.close()
                        pack_index += 1; pack_size = 0
                        pack_name = f"objects-{pack_index:03d}.pack"
                        stream = (output / pack_name).open("wb")
                    manifest["objects"][digest] = {"pack": pack_name, "offset": pack_size,
                                                   "compressed_bytes": len(compressed), "bytes": len(raw)}
                    stream.write(compressed); pack_size += len(compressed)
            manifest["files"][name] = recipe
    finally:
        if stream is not None: stream.close()
    for path in sorted(output.glob("objects-*.pack")):
        manifest["packs"][path.name] = {"bytes": path.stat().st_size, "sha256": sha256(path)}
    manifest["logical_bytes"] = sum(f["bytes"] for f in manifest["files"].values())
    manifest["stored_bytes"] = sum(f["bytes"] for f in manifest["packs"].values())
    (output / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    return manifest


def verify_or_extract(bundle, output=None):
    manifest = json.loads((bundle / "manifest.json").read_text())
    if (manifest["schema"], manifest["architecture"], manifest["cpu_subtype"], manifest["isa_version"]) != (1, "H13G", 4, 7):
        raise ValueError("Expected an M1 H13G/ISA7 reference bundle")
    if output is not None and output.exists():
        raise ValueError(f"Use a fresh extraction directory: {output}")
    for name, info in manifest["packs"].items():
        path = bundle / relative_path(name)
        if path.stat().st_size != info["bytes"] or sha256(path) != info["sha256"]:
            raise ValueError(f"Pack hash mismatch: {name}")
    for name, recipe in manifest["files"].items():
        relative = relative_path(name)
        path = output / relative if output is not None else None
        if path is not None: path.parent.mkdir(parents=True, exist_ok=True)
        dest = path.open("wb") if path is not None else None
        result = hashlib.sha256(); count = 0; header = b""
        try:
            for digest in recipe["chunks"]:
                info = manifest["objects"][digest]
                with (bundle / relative_path(info["pack"])).open("rb") as source:
                    source.seek(info["offset"])
                    raw = gzip.decompress(source.read(info["compressed_bytes"]))
                if len(raw) != info["bytes"] or hashlib.sha256(raw).hexdigest() != digest:
                    raise ValueError(f"Chunk hash mismatch: {name}")
                if not header: header = raw[:32]
                result.update(raw); count += len(raw)
                if dest is not None: dest.write(raw)
        finally:
            if dest is not None: dest.close()
        if count != recipe["bytes"] or result.hexdigest() != recipe["sha256"]:
            raise ValueError(f"Reconstructed file hash mismatch: {name}")
        if name.endswith("/model.hwx") and struct.unpack("<3I", header[:12]) != (0xBEEFFACE, 128, 4):
            raise ValueError(f"Wrong HWX architecture: {name}")
    if output is not None:
        # Recreate coefficient/data segments at the decoder's original paths.
        for name in manifest["files"]:
            if not name.endswith("/model.hwx"): continue
            hwx = output / relative_path(name)
            decoded = hwx.with_name("model.hwx-decoded")
            container = json.loads((decoded / "container.json").read_text())
            payloads = decoded / "payloads"; payloads.mkdir(exist_ok=True)
            with hwx.open("rb") as source:
                for i, segment in enumerate(container["segments"]):
                    source.seek(segment["fileoff"]); raw = source.read(segment["filesize"])
                    if hashlib.sha256(raw).hexdigest() != segment["payload_sha256"]:
                        raise ValueError(f"Decoded segment hash mismatch: {name}, segment {i}")
                    (payloads / f"segment-{i}.bin").write_bytes(raw)
    return manifest


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    sub = ap.add_subparsers(dest="command", required=True)
    build = sub.add_parser("pack")
    build.add_argument("--capture", type=Path, required=True)
    build.add_argument("--out", type=Path, required=True)
    check = sub.add_parser("verify")
    check.add_argument("bundle", type=Path)
    extract = sub.add_parser("extract")
    extract.add_argument("bundle", type=Path)
    extract.add_argument("--out", type=Path, required=True)
    args = ap.parse_args()
    if args.command == "pack": manifest = pack(args.capture, args.out)
    else: manifest = verify_or_extract(args.bundle, args.out if args.command == "extract" else None)
    print(json.dumps({"files": len(manifest["files"]), "selected_cases": len(manifest["selected_cases"]),
                      "logical_bytes": manifest["logical_bytes"], "stored_bytes": manifest["stored_bytes"],
                      "packs": len(manifest["packs"]), "hashes_verified": args.command != "pack",
                      "offline_hwx_evaluated": False, "linux_replay_verified": False}, indent=2))


if __name__ == "__main__": main()
